/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.w3c.dom.*;
import javax.xml.parsers.*;
import java.io.*;

public class App {
    public static void main(String[] args) {
        try {
            File xmlFile = new File(App.class.getClassLoader().getResource("data.xml").getFile());

            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);

            doc.getDocumentElement().normalize();
            System.out.println("Root element: " + doc.getDocumentElement().getNodeName());

            // Example: Print all fields
            NodeList list = doc.getElementsByTagName("*");
            for (int i = 0; i < list.getLength(); i++) {
                Node node = list.item(i);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    System.out.println(node.getNodeName() + ": " + node.getTextContent().trim());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
